from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any
from datetime import datetime

class Memory(BaseModel):
 """The Processed Knowledge. This is what you actually see and search for in your Dashboard."""
 id: str = Field(..., description="Matches the Capture ID or a new UUID")
 capture_ref: str = Field(..., description="Link back to the original raw Capture document")
 user_id: str = Field(..., description="Owner ID for Firestore security rules")
 
 # AI Generated Content
 title: str = Field(..., description="A short, catchy title generated by Gemini")
 one_line_summary: str = Field(..., description="A single sentence explaining exactly what this is")
 key_takeaways: List[str] = Field(default_factory=list, description="Bullet points of the most important info")
 full_transcript: Optional[str] = Field(None, description="The combined OCR text and Audio transcript")
 
 # Classification (The 'Cognition' part)
 category: str = Field(..., description="High-level bucket: 'Work', 'Personal', 'Finance', 'Inspiration', etc.")
 intent: str = Field(..., description="The primary goal: 'Task', 'Reference', 'Learning', 'Purchase'")
 priority: int = Field(default=1, ge=1, le=5, description="Priority score from 1 (Low) to 5 (Critical)")
 sentiment: str = Field("neutral", description="Emotional tone: 'positive', 'negative', 'urgent', or 'neutral'")
 
 # Structured Data for Search
 tags: List[str] = Field(default_factory=list, description="AI-generated hashtags for filtering")
 entities: Dict[str, List[str]] = Field(
 default_factory=dict, 
 description="Extracted People, Organizations, Dates, and Prices"
 )
 
 # Vector Search Support
 is_vectorized: bool = Field(default=False, description="Whether this memory has been embedded in Vertex AI")
 vector_id: Optional[str] = Field(None, description="The ID inside the Vector Database index")
 
 updated_at: datetime = Field(default_factory=datetime.utcnow)